#ifndef EXAMPLES_CPP_SOURCE_GROUP_TESTING_ABOVE_TREE_INNER_MAIN_H_
#define EXAMPLES_CPP_SOURCE_GROUP_TESTING_ABOVE_TREE_INNER_MAIN_H_

void foo() { }

#endif  // EXAMPLES_CPP_SOURCE_GROUP_TESTING_ABOVE_TREE_INNER_MAIN_H_
